# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/mnt/c/Users/EnricPuigvert/OneDrive - Fides Electronica/Development/Software/utilities/lvgl_sim/lv_port_pc_vscode"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/mnt/c/Users/EnricPuigvert/OneDrive - Fides Electronica/Development/Software/utilities/lvgl_sim/lv_port_pc_vscode"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/c/Users/EnricPuigvert/OneDrive - Fides Electronica/Development/Software/utilities/lvgl_sim/lv_port_pc_vscode/CMakeFiles" "/mnt/c/Users/EnricPuigvert/OneDrive - Fides Electronica/Development/Software/utilities/lvgl_sim/lv_port_pc_vscode//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/c/Users/EnricPuigvert/OneDrive - Fides Electronica/Development/Software/utilities/lvgl_sim/lv_port_pc_vscode/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named run

# Build rule for target.
run: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run
.PHONY : run

# fast build rule for target.
run/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/build
.PHONY : run/fast

#=============================================================================
# Target rules for targets named eez-framework

# Build rule for target.
eez-framework: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 eez-framework
.PHONY : eez-framework

# fast build rule for target.
eez-framework/fast:
	$(MAKE) $(MAKESILENT) -f eez-framework/CMakeFiles/eez-framework.dir/build.make eez-framework/CMakeFiles/eez-framework.dir/build
.PHONY : eez-framework/fast

#=============================================================================
# Target rules for targets named lvgl

# Build rule for target.
lvgl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lvgl
.PHONY : lvgl

# fast build rule for target.
lvgl/fast:
	$(MAKE) $(MAKESILENT) -f lvgl/CMakeFiles/lvgl.dir/build.make lvgl/CMakeFiles/lvgl.dir/build
.PHONY : lvgl/fast

#=============================================================================
# Target rules for targets named lvgl_thorvg

# Build rule for target.
lvgl_thorvg: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lvgl_thorvg
.PHONY : lvgl_thorvg

# fast build rule for target.
lvgl_thorvg/fast:
	$(MAKE) $(MAKESILENT) -f lvgl/CMakeFiles/lvgl_thorvg.dir/build.make lvgl/CMakeFiles/lvgl_thorvg.dir/build
.PHONY : lvgl_thorvg/fast

#=============================================================================
# Target rules for targets named lvgl_examples

# Build rule for target.
lvgl_examples: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lvgl_examples
.PHONY : lvgl_examples

# fast build rule for target.
lvgl_examples/fast:
	$(MAKE) $(MAKESILENT) -f lvgl/CMakeFiles/lvgl_examples.dir/build.make lvgl/CMakeFiles/lvgl_examples.dir/build
.PHONY : lvgl_examples/fast

#=============================================================================
# Target rules for targets named lvgl_demos

# Build rule for target.
lvgl_demos: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lvgl_demos
.PHONY : lvgl_demos

# fast build rule for target.
lvgl_demos/fast:
	$(MAKE) $(MAKESILENT) -f lvgl/CMakeFiles/lvgl_demos.dir/build.make lvgl/CMakeFiles/lvgl_demos.dir/build
.PHONY : lvgl_demos/fast

main/src/main.o: main/src/main.c.o
.PHONY : main/src/main.o

# target to build an object file
main/src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main/src/main.c.o
.PHONY : main/src/main.c.o

main/src/main.i: main/src/main.c.i
.PHONY : main/src/main.i

# target to preprocess a source file
main/src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main/src/main.c.i
.PHONY : main/src/main.c.i

main/src/main.s: main/src/main.c.s
.PHONY : main/src/main.s

# target to generate assembly for a file
main/src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main/src/main.c.s
.PHONY : main/src/main.c.s

main/src/mouse_cursor_icon.o: main/src/mouse_cursor_icon.c.o
.PHONY : main/src/mouse_cursor_icon.o

# target to build an object file
main/src/mouse_cursor_icon.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main/src/mouse_cursor_icon.c.o
.PHONY : main/src/mouse_cursor_icon.c.o

main/src/mouse_cursor_icon.i: main/src/mouse_cursor_icon.c.i
.PHONY : main/src/mouse_cursor_icon.i

# target to preprocess a source file
main/src/mouse_cursor_icon.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main/src/mouse_cursor_icon.c.i
.PHONY : main/src/mouse_cursor_icon.c.i

main/src/mouse_cursor_icon.s: main/src/mouse_cursor_icon.c.s
.PHONY : main/src/mouse_cursor_icon.s

# target to generate assembly for a file
main/src/mouse_cursor_icon.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/main/src/mouse_cursor_icon.c.s
.PHONY : main/src/mouse_cursor_icon.c.s

ui/flow_def.o: ui/flow_def.c.o
.PHONY : ui/flow_def.o

# target to build an object file
ui/flow_def.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/ui/flow_def.c.o
.PHONY : ui/flow_def.c.o

ui/flow_def.i: ui/flow_def.c.i
.PHONY : ui/flow_def.i

# target to preprocess a source file
ui/flow_def.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/ui/flow_def.c.i
.PHONY : ui/flow_def.c.i

ui/flow_def.s: ui/flow_def.c.s
.PHONY : ui/flow_def.s

# target to generate assembly for a file
ui/flow_def.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/ui/flow_def.c.s
.PHONY : ui/flow_def.c.s

ui/images.o: ui/images.c.o
.PHONY : ui/images.o

# target to build an object file
ui/images.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/ui/images.c.o
.PHONY : ui/images.c.o

ui/images.i: ui/images.c.i
.PHONY : ui/images.i

# target to preprocess a source file
ui/images.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/ui/images.c.i
.PHONY : ui/images.c.i

ui/images.s: ui/images.c.s
.PHONY : ui/images.s

# target to generate assembly for a file
ui/images.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/ui/images.c.s
.PHONY : ui/images.c.s

ui/screens.o: ui/screens.c.o
.PHONY : ui/screens.o

# target to build an object file
ui/screens.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/ui/screens.c.o
.PHONY : ui/screens.c.o

ui/screens.i: ui/screens.c.i
.PHONY : ui/screens.i

# target to preprocess a source file
ui/screens.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/ui/screens.c.i
.PHONY : ui/screens.c.i

ui/screens.s: ui/screens.c.s
.PHONY : ui/screens.s

# target to generate assembly for a file
ui/screens.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/ui/screens.c.s
.PHONY : ui/screens.c.s

ui/styles.o: ui/styles.c.o
.PHONY : ui/styles.o

# target to build an object file
ui/styles.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/ui/styles.c.o
.PHONY : ui/styles.c.o

ui/styles.i: ui/styles.c.i
.PHONY : ui/styles.i

# target to preprocess a source file
ui/styles.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/ui/styles.c.i
.PHONY : ui/styles.c.i

ui/styles.s: ui/styles.c.s
.PHONY : ui/styles.s

# target to generate assembly for a file
ui/styles.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/ui/styles.c.s
.PHONY : ui/styles.c.s

ui/ui.o: ui/ui.c.o
.PHONY : ui/ui.o

# target to build an object file
ui/ui.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/ui/ui.c.o
.PHONY : ui/ui.c.o

ui/ui.i: ui/ui.c.i
.PHONY : ui/ui.i

# target to preprocess a source file
ui/ui.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/ui/ui.c.i
.PHONY : ui/ui.c.i

ui/ui.s: ui/ui.c.s
.PHONY : ui/ui.s

# target to generate assembly for a file
ui/ui.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/ui/ui.c.s
.PHONY : ui/ui.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... run"
	@echo "... eez-framework"
	@echo "... lvgl"
	@echo "... lvgl_demos"
	@echo "... lvgl_examples"
	@echo "... lvgl_thorvg"
	@echo "... main"
	@echo "... main/src/main.o"
	@echo "... main/src/main.i"
	@echo "... main/src/main.s"
	@echo "... main/src/mouse_cursor_icon.o"
	@echo "... main/src/mouse_cursor_icon.i"
	@echo "... main/src/mouse_cursor_icon.s"
	@echo "... ui/flow_def.o"
	@echo "... ui/flow_def.i"
	@echo "... ui/flow_def.s"
	@echo "... ui/images.o"
	@echo "... ui/images.i"
	@echo "... ui/images.s"
	@echo "... ui/screens.o"
	@echo "... ui/screens.i"
	@echo "... ui/screens.s"
	@echo "... ui/styles.o"
	@echo "... ui/styles.i"
	@echo "... ui/styles.s"
	@echo "... ui/ui.o"
	@echo "... ui/ui.i"
	@echo "... ui/ui.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

